apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devsecops-theo
  name: devsecops-theo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops-theo
  strategy: {}
  template:
    metadata:
      labels:
        app: devsecops-theo
    spec:
      volumes:
      - name: vol
        emptyDir: {}
      serviceAccountName: default
      containers:
      - image: replace
        name: devsecops-theo-container
        volumeMounts:
        - mountPath: /tmp
          name: vol
        securityContext:
          runAsNonRoot: true
          runAsUser: 100
          readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devsecops-theo
  name: devsecops-theo-svc
spec:
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: devsecops-theo
  type: NodePort
